export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-oid="5l911u1">
      <body data-oid="-m5d:3l">{children}</body>
    </html>
  );
}
